name: Docker Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # Allow manual triggering

jobs:
  docker:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    # Ensure data directories exist
    - name: Create data directories
      run: |
        mkdir -p data/documents
        mkdir -p data/summaries
        touch data/documents/.gitkeep
        touch data/summaries/.gitkeep
        echo "Data directories created for Docker build"
    
    # Build and test the lite version (preferred for most users)
    - name: Build Docker image (Lite Version)
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile.lite
        push: false
        load: true  # Load the image into the Docker daemon
        tags: researchgpt:lite-test
        cache-from: type=gha
        cache-to: type=gha,mode=max
    
    - name: Verify Lite Docker image
      run: |
        # Run the container with --help to verify it starts correctly
        docker run --rm researchgpt:lite-test --help
        echo "Lite Docker image verification complete"
    
    # Build Alpine version (full dependencies)
    - name: Build Docker image (Alpine)
      if: success() # Only run if lite version succeeded
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: false
        load: true  # Load the image into the Docker daemon
        tags: researchgpt:alpine-test
        cache-from: type=gha
        cache-to: type=gha,mode=max
    
    - name: Verify Alpine Docker image
      if: success() # Only run if Alpine build succeeded
      run: |
        # Run the container with --help to verify it starts correctly
        docker run --rm researchgpt:alpine-test --help
        echo "Alpine Docker image verification complete"
        
    # Build Debian version (full dependencies, different base image)
    - name: Build Docker image (Debian)
      if: success() # Only run if previous builds succeeded
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile.debian
        push: false
        load: true  # Load the image into the Docker daemon
        tags: researchgpt:debian-test
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Verify Debian Docker image
      if: success() # Only run if Debian build succeeded
      run: |
        docker run --rm researchgpt:debian-test --help
        echo "Debian Docker image verification complete"
    
    # Verify with environment
    - name: Environment verification test
      if: success()
      run: |
        # Create an .env file for testing
        cp .env.example .env
        echo "OLLAMA_BASE_URL=http://mock-ollama:11434" >> .env
        echo "OLLAMA_MODEL=test-model" >> .env
        
        # Run the lite container with environment file
        docker run --rm --env-file .env researchgpt:lite-test --help
        
        echo "Docker image environment verification complete" 