name: Python Linting

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # Allow manual triggering

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 black isort ruff
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: Lint with Ruff
      run: |
        ruff check .
      continue-on-error: true  # Don't fail the workflow for Ruff warnings
    
    - name: Check formatting with black
      run: |
        black --check --diff .
      continue-on-error: true  # Don't fail the workflow if formatting is off
    
    - name: Check import sorting with isort
      run: |
        isort --check-only --diff .
      continue-on-error: true  # Don't fail the workflow if imports are not sorted 