name: Python Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # Allow manual triggering

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11', '3.12']

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov requests-mock
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Run tests
      run: |
        # Run only non-interactive tests
        pytest --cov=agent --ignore=tests/test_cli_summary.py tests/
      env:
        PYTHONPATH: ${{ github.workspace }}
        # Set dummy Ollama URLs for tests, actual calls will be mocked
        OLLAMA_BASE_URL: http://mock-ollama:11434 
        OLLAMA_MODEL: test-model
        OLLAMA_EMBED_MODEL: test-embed-model 