name: Release

on:
  release:
    types: [published]
  workflow_dispatch:  # Allow manual triggering

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Extract metadata for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: |
          ghcr.io/${{ github.repository }}
        tags: |
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=ref,event=branch
          type=sha,format=short
          latest
    
    # Build and push lite version (default)
    - name: Build and push Docker image (Lite)
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile.lite
        push: true
        tags: |
          ghcr.io/${{ github.repository }}:latest
          ghcr.io/${{ github.repository }}:lite
          ghcr.io/${{ github.repository }}:${{ steps.meta.outputs.version }}-lite
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
    
    # Build and push Alpine version
    - name: Build and push Docker image (Alpine)
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          ghcr.io/${{ github.repository }}:alpine
          ghcr.io/${{ github.repository }}:${{ steps.meta.outputs.version }}-alpine
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
    
    # Build and push Debian version
    - name: Build and push Docker image (Debian)
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile.debian
        push: true
        tags: |
          ghcr.io/${{ github.repository }}:debian
          ghcr.io/${{ github.repository }}:${{ steps.meta.outputs.version }}-debian
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max 